"""Compute KB + test-set statistics and (re)write the Dataset section of RESULTS.md.

Idempotent: replaces the block between the AUTO markers, leaving any prose you
add outside them intact.

  python -m data.stats
"""
from __future__ import annotations

import collections
import json
import statistics
from datetime import date

from .common import KB, ROOT, TESTSET, read_jsonl

BEGIN = "<!-- AUTO:DATASET:BEGIN -->"
END = "<!-- AUTO:DATASET:END -->"


def md_table(headers, rows):
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def build():
    chunks = read_jsonl(KB / "chunks.jsonl")
    docs = {f.stem: read_jsonl(f) for f in KB.glob("docs_*.jsonl")}
    surv_stats = json.load(open(TESTSET / "attackqa_survival_stats.json"))
    build_log = json.load(open(TESTSET / "build_log.json"))
    ver = json.load(open(TESTSET / "verification_stats.json"))
    queries = read_jsonl(TESTSET / "queries.jsonl")
    sel = json.load(open(ROOT / "raw" / "nvd" / "selection.json"))

    L = [f"_Generated by `python -m data.stats` on {date.today()}._\n"]

    # KB composition
    L.append("### Knowledge base composition\n")
    n_docs = sum(len(v) for v in docs.values())
    L.append(f"The KB is **{n_docs} documents → {len(chunks)} chunks** from three sources:\n")
    src_rows = []
    by_src_docs = collections.Counter()
    for d in [x for v in docs.values() for x in v]:
        by_src_docs[d["source"]] += 1
    by_src_ch = collections.Counter(c["source_context"]["source"] for c in chunks)
    for s in sorted(by_src_ch, key=lambda s: -by_src_ch[s]):
        src_rows.append([s, by_src_docs[s], by_src_ch[s]])
    L.append(md_table(["Source", "Documents", "Chunks"], src_rows) + "\n")

    et = collections.Counter(c["source_context"]["entity_type"] for c in chunks)
    L.append("Chunks by entity type: " + ", ".join(f"{k} {v}" for k, v in et.most_common()) + ".\n")

    words = [c["n_words"] for c in chunks]
    L.append(f"Chunk length (words): min {min(words)}, median {int(statistics.median(words))}, "
             f"mean {statistics.mean(words):.0f}, max {max(words)}; "
             f"{sum(1 for c in chunks if c['source_context']['n_parts'] > 1)} chunks come from "
             f"sections split at the {max(words)}-word cap.\n")

    # CVE selection
    L.append("### CVE slice (NVD)\n")
    rc = collections.Counter(v["reason"].split(":")[0] for v in sel.values())
    L.append(f"{len(sel)} CVE cards, selected programmatically: "
             + ", ".join(f"{k} {v}" for k, v in rc.most_common()) + ".\n")

    # AttackQA survival
    L.append("### AttackQA survival against ATT&CK v19.2\n")
    L.append(f"AttackQA was built on ATT&CK v15.1; this KB indexes v19.2. Of "
             f"**{surv_stats['total']} rows, {surv_stats['survived']} "
             f"({surv_stats['survival_rate']:.1%}) survive** the mechanical filter "
             f"(document fact still present verbatim / as an equal ID-set in the rendered KB). "
             f"A further {surv_stats['answer_span_survives_among_failed']} rows survive if only "
             f"the answer span (not the whole document) must persist "
             f"({surv_stats['loose_survival_rate']:.1%}).\n")
    rows = []
    for s, st in surv_stats["by_source"].items():
        reasons = "; ".join(f"{k[8:]}: {v}" for k, v in st.items() if k.startswith("reason"))
        rows.append([s, st["total"], st["survived"], f"{st['survived']/st['total']:.0%}", reasons[:70]])
    L.append(md_table(["AttackQA template", "rows", "survived", "%", "main failure reason"], rows) + "\n")
    L.append("_The two 0% templates (`relationships_detects`, `relationships_detections_summaries`, "
             "3,965 rows / 15.6% of AttackQA) are structurally unsupported: ATT&CK v18 replaced "
             "per-data-component detection notes with detection-strategy/analytic objects._\n")

    # Test set
    L.append("### Test-query set\n")
    L.append(f"**{build_log['total']} queries** (seed {build_log['seed']}), stratified by "
             f"retrieval/grounding difficulty, spanning {build_log['n_tactics']} ATT&CK tactics "
             f"({', '.join(build_log['tactics_covered'])}).\n")
    catmap = {"lookup_id": "A lookup, ID in question (AttackQA)",
              "lookup_nl": "B lookup, ID-free NL (AttackQA)",
              "aggregate": "C aggregate/list (AttackQA)",
              "multihop": "D multi-hop synthesis (self)",
              "confusability": "E parent/sub & near-name confusability (self)",
              "cve_fact": "F CVE structured fact (self)",
              "source_conflict": "G CNA-vs-NVD conflict (self)",
              "nist": "H NIST prose + table (self)",
              "near_miss": "I near-miss unsupported → abstain (self)",
              "out_of_scope": "J out-of-scope (self)",
              "ambiguous": "K ambiguous → clarify (self)",
              "dual_use": "L dual-use → refuse (self)",
              "cve_desc": "CVE-desc → CWE, ID-free (self/NVD)"}
    beh = {q["qid"]: q["expected_behaviour"] for q in queries}
    rows = [[catmap.get(c, c), n, ", ".join(sorted({beh[q["qid"]] for q in queries if q["category"] == c}))]
            for c, n in build_log["by_category"].items()]
    L.append(md_table(["Category", "n", "expected behaviour"], rows) + "\n")
    L.append("Expected behaviour overall: "
             + ", ".join(f"{k} {v}" for k, v in build_log["by_expected_behaviour"].items()) + ".\n")

    # Verification
    L.append("### Gold-label verification\n")
    cm = ver["tier3_microgold"]["confusion"]
    L.append(f"- **Tier 1 (deterministic):** {ver['tier1']['pass']}/{ver['tier1']['pass']} answerable "
             f"items' declared gold facts are present verbatim in their gold chunks "
             f"(0 failures).\n"
             f"- **Tier 2 (constrained entailment, Worker `generator` model):** "
             f"{ver['tier2']['ran']} gold answers not already verbatim in their chunks were checked; "
             f"{ver['tier2']['ran'] - len(ver['tier2']['fail'])} entailed, "
             f"{len(ver['tier2']['fail'])} flagged"
             + (f" ({', '.join(ver['tier2']['fail'])})" if ver['tier2']['fail'] else "") + ".\n"
             f"- **Tier 3 (micro-gold calibration):** {ver['tier3_microgold']['n_pairs']} genuine+corrupted "
             f"pairs; the Tier-2 checker scored accuracy **{ver['tier3_microgold']['accuracy']:.0%}** "
             f"(TP {cm['tp']}, TN {cm['tn']}, FP {cm['fp']}, FN {cm['fn']}) — it never rejected a genuine "
             f"answer but accepted {cm['fp']} corrupted ones, i.e. the automated checker is lenient, "
             f"not strict. This is a measured property of the curation method, reported rather than assumed.\n"
             f"- **Worker cost for verification:** {ver['worker_neurons']:.0f} neurons "
             f"(of the 10,000/day free-tier pool).\n")
    return "\n".join(L)


def main():
    path = ROOT / "RESULTS.md"
    block = f"{BEGIN}\n\n{build()}\n{END}"
    if path.exists() and BEGIN in path.read_text():
        txt = path.read_text()
        pre, rest = txt.split(BEGIN, 1)
        _, post = rest.split(END, 1)
        path.write_text(pre + block + post)
    else:
        header = ("# Results\n\n"
                  "This file holds the full, unabridged results of the project; the LaTeX report "
                  "cites a curated subset. The Dataset section below is generated from the data-"
                  "construction pipeline (`data/`).\n\n## Dataset\n\n")
        path.write_text(header + block + "\n")
    print(f"wrote Dataset section -> {path}")


if __name__ == "__main__":
    main()
